# Format :  https://fr.wikipedia.org/wiki/Yaml#Caract%C3%A9ristiques
PrintMessage: 2                         # 0=0	5=debug
serial:
    port: /dev/ttyAMA0
    baudRate: 4800
    timeout: 0
    # Débit du serial 0 qui va vers l'Arduino (doit être cohérent entre les 2, diffère selon la distance de câble)
    # Débit   Longueur (m)
    # 2400   60
    # 4 800   30
    # 9 600   15
    # 19 200  7,6
    # https://fr.wikipedia.org/wiki/RS-232#Limites
dataPath: /tmp/PvMonit_vedirectOnAdruino.data.yaml
