# Format :  https://fr.wikipedia.org/wiki/Yaml#Caract%C3%A9ristiques
PrintMessage: 5                         # 0=0	5=debug
serial:
    port: /dev/ttyAMA0                  # ttyAMA0 pour le serial via GPIO, ttyUSB0 pour le port USB...
    timeout: 0
    baudRate: 4800
    # Débit du serial 0 qui va vers l'Arduino (doit être cohérent entre les 2, diffère selon la distance de câble)
    # Débit   Longueur (m)
    # 2400   60
    # 4 800   30
    # 9 600   15
    # 19 200  7,6
    # https://fr.wikipedia.org/wiki/RS-232#Limites
    whileSleep: 0.04                    # Temps d'attente dans la boucle, si le débit est rapide il faut diminuer se temps, sinon on peut l'augmenter pour que le processeur se soit pas à 100% pour rien...
                                        # 0.05 convient pour 4800 de débit
dataPath: /tmp/PvMonit_getSerialArduino.data.yaml  # Mettre un emplacement en tmpfs est préférable
