# Format :  https://fr.wikipedia.org/wiki/Yaml#Caract%C3%A9ristiques
PrintMessage: 5                         # 0=0	5=debug
i2c:
    adress: 0x04
    device: 1
HeartbeatTime: 1                       # Fréquence du bâtement de coeur (en seconde)
xmlData:
    file: /opt/PvMonit/www/data-xml-test.xml
    #fileExpir: 300                     # Age en seconde après laquel le fichier n'est plus considéré comme ok
    fileExpir: 30000
    checkTime: 10                        # Fréquece de la vérificatio du XML (en seconde)
    checkError: 3                        # nombre d'erreurs sur le xml avant de sortir du mode automatique / stopper le heartbeat
                                        # temps avant erreur = $XML_CHECK_TIME * $XML_CHECK_ERROR
    #expir: 600                      # Age en seconde après laquel la donnée n'est plus considérer comme viable
    expir: 600000                    # Age en seconde après laquel la donnée n'est plus considérer comme viable
    DownloadRetry: 3
    valueUse:
        0: SOC
        1: P
        2: PPVT
        3: CS
        #4: CONSO
relay:
    nb: 5
    scriptDir: ./relay.script.d/
    scriptExecInterval: 2              # Interval d'execution des script de relais
    correspondance:                     # A commencer par 0
        0: Box Internet
        1: Téléphone
        2: Disque dur externe
        3: Pompe de relevage
        4: Chargeur outil électroportatif

